apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: zgoalizt
spec:
  externalTrafficPolicy: Cluster
  selector:
    app: backer
  ports:
  - port: 3001
    targetPort: 3001
  type: LoadBalancer
